<?php
namespace TYPO3\Flow\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
	Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20121104032604 extends AbstractMigration {

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function up(Schema $schema) {
			// this up() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("ALTER TABLE ttree_iso_domain_model_country DROP PRIMARY KEY");
		$this->addSql("ALTER TABLE ttree_iso_domain_model_country CHANGE alpha2 alpha2 VARCHAR(255) DEFAULT NULL, CHANGE alpha4 alpha4 VARCHAR(255) DEFAULT NULL, CHANGE numericcode numericcode VARCHAR(255) DEFAULT NULL");
		$this->addSql("ALTER TABLE ttree_iso_domain_model_country ADD PRIMARY KEY (standard, alpha3)");
	}

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function down(Schema $schema) {
			// this down() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("ALTER TABLE ttree_iso_domain_model_country DROP PRIMARY KEY");
		$this->addSql("ALTER TABLE ttree_iso_domain_model_country CHANGE alpha2 alpha2 VARCHAR(255) NOT NULL, CHANGE alpha4 alpha4 VARCHAR(255) NOT NULL, CHANGE numericcode numericcode VARCHAR(255) NOT NULL");
		$this->addSql("ALTER TABLE ttree_iso_domain_model_country ADD PRIMARY KEY (alpha2, alpha3, alpha4, numericcode)");
	}
}

?>