<?php
namespace TYPO3\Flow\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
	Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20121104032934 extends AbstractMigration {

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function up(Schema $schema) {
			// this up() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("ALTER TABLE ttree_iso_domain_model_language DROP PRIMARY KEY");
		$this->addSql("ALTER TABLE ttree_iso_domain_model_language ADD standard VARCHAR(10) NOT NULL");
		$this->addSql("ALTER TABLE ttree_iso_domain_model_language ADD PRIMARY KEY (standard, id)");
	}

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function down(Schema $schema) {
			// this down() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("ALTER TABLE ttree_iso_domain_model_language DROP PRIMARY KEY");
		$this->addSql("ALTER TABLE ttree_iso_domain_model_language DROP standard");
		$this->addSql("ALTER TABLE ttree_iso_domain_model_language ADD PRIMARY KEY (id)");
	}
}

?>